server:
  port: 8082
spring:
  application:
    name: wishlist
  data:
    mongodb:
      uri: mongodb://localhost:27017/wishlist_db
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
