version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: wishlist-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wishlist-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-express:
    image: mongo-express:1.0.0
    container_name: wishlist-mongo-express
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - wishlist-network

volumes:
  mongodb_data:
    driver: local

networks:
  wishlist-network:
    driver: bridge